//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceWatcher) DeepCopyInto(out *NamespaceWatcher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceWatcher.
func (in *NamespaceWatcher) DeepCopy() *NamespaceWatcher {
	if in == nil {
		return nil
	}
	out := new(NamespaceWatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceWatcher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceWatcherList) DeepCopyInto(out *NamespaceWatcherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamespaceWatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceWatcherList.
func (in *NamespaceWatcherList) DeepCopy() *NamespaceWatcherList {
	if in == nil {
		return nil
	}
	out := new(NamespaceWatcherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceWatcherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceWatcherSpec) DeepCopyInto(out *NamespaceWatcherSpec) {
	*out = *in
	in.NamespaceLabelSelector.DeepCopyInto(&out.NamespaceLabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceWatcherSpec.
func (in *NamespaceWatcherSpec) DeepCopy() *NamespaceWatcherSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceWatcherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceWatcherStatus) DeepCopyInto(out *NamespaceWatcherStatus) {
	*out = *in
	in.SecretStatus.DeepCopyInto(&out.SecretStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceWatcherStatus.
func (in *NamespaceWatcherStatus) DeepCopy() *NamespaceWatcherStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceWatcherStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStatus) DeepCopyInto(out *SecretStatus) {
	*out = *in
	if in.KeyHashes != nil {
		in, out := &in.KeyHashes, &out.KeyHashes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStatus.
func (in *SecretStatus) DeepCopy() *SecretStatus {
	if in == nil {
		return nil
	}
	out := new(SecretStatus)
	in.DeepCopyInto(out)
	return out
}
